### ISSUE TITLE
SGX Disable - How to?

### ISSUE THREAD

**Issue by ArneTR** [intel/sgx-software-enable#6]
I am running a BIOS that does not expose any functionality for enabling/disabling SGX.

However my CPU does technically support SGX.

This script here also works for me and I could turn on SGX. After testing I now want to turn it off again, but I see no option or hint provided how to do so.

How is it possible to turn SGX off again through the EFI method? Or is there any other method available that does not require to have the setting configurable in the BIOS?

I already search the *Intel® 64 and IA-32 Architectures Software Developer’s Manual* but found not info about how to disable without BIOS.

**Comment by jmechalas** [comment]
Once SGX is enabled it cannot be disabled via software. The intent here is to prevent malicious software from disabling SGX and thus reverting the system to non-SGX code paths without the user's knowledge.

Updating the BIOS, or reflashing the existing one, should reset the SGX state if you don't have an explicit method for disabling it in the BIOS.

**Comment by ArneTR** [comment]
Thank you for the quick reply, really appreciated!
